apiVersion: 1

datasources:
  - name: Prometheus        # nhãn trong dropdown; đặt trùng tên nguồn cho dễ đọc
    type: prometheus        # plugin ID, viết thường
    access: proxy
    url: http://prometheus:9090   # tên service trong docker-compose + cổng trong container
    isDefault: true